# Generated by Django 4.2.6 on 2023-11-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='year',
            field=models.CharField(default='NY', max_length=4),
            preserve_default=False,
        ),
    ]
