# Generated by Django 4.2.6 on 2023-11-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
